version: '3'

volumes:
  nexus_sonatype_work:

networks:
  default:
    external:
      name: ${CUSTOM_NETWORK_NAME}

services:
  nexus:
    container_name: nexus
    restart: always
    image: liatrio/ldop-nexus:0.1.6
    #build: . 
    depends_on:
      - "elasticsearch"
      - "logstash"
      - "kibana"
    expose:
      - "8081"
    environment:
      NEXUS_BASE_URL: "${PROTO}://${TARGET_HOST}/nexus"
      LDAP_SEARCH_BASE: "${LDAP_FULL_DOMAIN}"
      LDAP_ENABLED: "true"
      LDAP_URL: "ldap"
      LDAP_BIND_DN: "${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
      LDAP_USER_PASSWORD_ATTRIBUTE: "userPassword"
      LDAP_USER_BASE_DN: "${LDAP_USER_BASE_DN}"
      LDAP_GROUP_BASE_DN: "${LDAP_GROUP_BASE_DN}"
      LDAP_BIND_PASSWORD: ${LDAP_PWD}
    volumes:
      - nexus_sonatype_work:/sonatype-work
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        tag: "nexus"

