version: '3'

volumes:
  nexus_sonatype_work:

networks:
  default:
    external:
      name: ${CUSTOM_NETWORK_NAME}

services:
  nexus:
    image: accenture/adop-nexus:0.1.3
    depends_on:
      - "elasticsearch"
      - "logstash"
      - "kibana"
    environment:
      NEXUS_BASE_URL: "${PROTO}://${TARGET_HOST}/nexus"
      LDAP_SEARCH_BASE: "${LDAP_FULL_DOMAIN}"
      LDAP_ENABLED: "true"
      LDAP_URL: "ldap"
      LDAP_BIND_DN: "${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
      LDAP_USER_PASSWORD_ATTRIBUTE: "userPassword"
      LDAP_USER_BASE_DN: "${LDAP_USER_BASE_DN}"
      LDAP_GROUP_BASE_DN: "${LDAP_GROUP_BASE_DN}"
      LDAP_BIND_PASSWORD: ${LDAP_PWD}
    volumes:
      - nexus_sonatype_work:/sonatype-work
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        tag: "nexus"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
