version: '3'

volumes: 
  test_elasticsearch_data:
  test_nginx_config:
  test_nginx_releasenote:
  test_ldap_db:
  test_ldap_static:
  test_gerrit_mysql_data:
  test_git_repos:
  test_gerrit_review_site:
  test_sensu_api_conf:
  test_sensu_server_conf:
  test_sensu_client_conf:
  test_sensu_rabbitmq_data:
  test_sensu_redis_data:
  test_sonar_mysql_data:
  test_sonar_data:
  test_sonar_extensions:
  test_sonar_logs:
  test_jenkins_slave_home:
  test_jenkins_home:
  test_jenkins_home:
  test_nexus_sonatype_work:
  test_registry_certs:
  test_registry_data:

services:
  elasticsearch:
    volumes:
      - test_elasticsearch_data:/usr/share/elasticsearch/data

  proxy:
    volumes:
      - test_nginx_config:/etc/nginx
      - test_nginx_releasenote:/usr/share/nginx/html

  ldap:
    volumes:
        - test_ldap_db:/var/lib/ldap
        - test_ldap_static:/etc/ldap

  gerrit-mysql:
    volumes:
      - test_gerrit_mysql_data:/var/lib/mysql

  gerrit:
    user: root
    volumes:
      - test_git_repos:/var/git/repos 
      - test_gerrit_review_site:/var/gerrit/review_site 

  sensu-api:
    volumes:
      - test_sensu_api_conf:/etc/sensu/conf.d

  sensu-server:
    volumes:
      - test_sensu_server_conf:/etc/sensu/conf.d

  sensu-client:
    volumes:
      - test_sensu_client_conf:/etc/sensu/conf.d

  sensu-rabbitmq:
    volumes:
      - test_sensu_rabbitmq_data:/var/lib/rabbitmq

  sensu-redis:
    volumes:
      - test_sensu_redis_data:/data

  sonar-mysql:
    volumes:
      - test_sonar_mysql_data:/var/lib/mysql 

  sonar:
    volumes:
      - test_sonar_data:/opt/sonarqube/data
      - test_sonar_extensions:/opt/sonarqube/extensions 
      - test_sonar_logs:/opt/sonarqube/logs

  jenkins-slave:
    volumes:
      - test_jenkins_slave_home:/workspace
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins:
    user: root 
    volumes:
      - test_jenkins_home:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock

  nexus:
    volumes:
      - test_nexus_sonatype_work:/sonatype-work

  registry:
    volumes:
      - test_registry_certs:/certs
      - test_registry_data:/data

