#!/bin/bash

SUB_CMD_NAME="test"

cmd_desc() {
    echo "For confirming LDOP functionality during development."
}

cmd_usage() {
    echo "usage: ${CMD_NAME} ${SUB_CMD_NAME} <subcommand>"
}

help() {
    cmd_usage echo
    echo "Available subcommands are:"
    printf "    %-20s   %s\n" "clean" "Test functionality given a clean environment."
    printf "    %-20s   %s\n" "help" "Prints this help information"
    echo
}

clean() {
  echo
  echo "#######################"
  echo "# Testing in Progress #"
  echo "#######################"
  echo
  sleep 1

  #./cmd/compose down --volumes
  #./cmd/compose init --without-pull

  # The URL of the job Load_Platform as hit from within the Jenkins container
  JOB_URL=localhost:8080/jenkins/job/Load_Platform

  # A value to determine if the job is currently executing
  GREP_RETURN_CODE=0

  # Sources to obtain the password for Jenkins
  source ${CONF_DIR}/conf/env.provider.sh
  source ${CONF_DIR}/credentials.generate.sh
  source ${CONF_DIR}/env.config.sh 

  # Trigger the parameterized job with default parameters.
  # -s silent, don't output curl details
  # docker exec jenkins, execute from within jenkins container
  # --data '', execute the curl as a POST
  # /buildWithParameters, build with default parameters
  docker exec jenkins curl -s --data '' jenkins:${PASSWORD_JENKINS}@${JOB_URL}/buildWithParameters
  echo "...triggered the job Load_Platform to build with default parameters..."

  # Disable -e as set in ADOP...
  set +e

  # ...while the successful curl of the lastBuild information
  # holds a null value as the result...
  # "while the job is still executing"
  while [ $GREP_RETURN_CODE -eq 0 ]
  do
    # Give the job time to build, check every 30 seconds
    echo "...waiting 30 seconds for Load_Platform job to execute..."
    sleep 30
    CURL=$(docker exec jenkins curl -s jenkins:${PASSWORD_JENKINS}@${JOB_URL}/lastBuild/api/json)
    # If the curl command did not error...
    # (only update the "job currently executing" variable if the curl succeeds)
    if [ $? -eq 0 ]
    then
      # Grep will return 0 (successfully obtained null result) 
      # while the build is running
      echo $CURL | grep result\":null > /dev/null
      GREP_RETURN_CODE=$?
    fi
    # If the curl command errored, sleep and try again
  done
  RESULT=$(echo $CURL | grep -E -o "result\":.{0,10}" | awk -F'"' '{print $3}')
  echo "...Load_Platform job completed! Build Status: $RESULT"

  set -e

  echo
  echo "#######################"
  echo "#  Testing Complete   #"
  echo "#######################"
  echo
}

shift $(($OPTIND -1))
SUBCOMMAND_OPT="${1:-help}"

# Only shift if there are other parameters
if [ $# -ge 1 ]; then
    shift
fi

if [ ! -z ${SUBCOMMAND_OPT} ]; then
  case ${SUBCOMMAND_OPT} in
    "cmd_desc"|"help")
        ${SUBCOMMAND_OPT}
        ;;
    "clean")
        clean
        ;;
    *)
        echo "Invalid subcommand."
        help
        exit 1
        ;;
  esac
fi
