version: '3'

volumes:
  artifactory_data:

networks:
  default:
    external:
      name: ${CUSTOM_NETWORK_NAME}

services:
  artifactory:
    container_name: artifactory
    restart: always
    image: liatrio/ldop-artifactory:0.0.1
    build: extensions/artifactory
    expose:
      - "8081"
    ports:
      - "8081:8081"
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    environment:
      - LDAP_PWD
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        tag: "artifactory"

