version: '3'

volumes:
  artifactory_data:

services:
  artifactory:
    container_name: artifactory
    restart: always
    build: extensions/artifactory
    expose:
      - "8081"
    ports:
      - "8081:8081"
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    environment:
      - LDAP_PWD
      - LDAP_DOMAIN
      - INITIAL_ADMIN_USER
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        tag: "artifactory"

