version: '3'

volumes:
  nexus3_sonatype_work:

networks:
  default:
    external:
      name: ${CUSTOM_NETWORK_NAME}

services:
  nexus:
    image: accenture/adop-nexus:0.1.3
    depends_on:
      - "elasticsearch"
      - "logstash"
      - "kibana"
    expose:
      - "8081"
    environment:

    volumes:
      - nexus3_sonatype_work
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        tag: "nexus3"
